Update patch set 1
Patch Set 1:

I have a single intermittent test failure in
TestGenerateArtifactsServiceImpl.testGenerateArtifacts:54

The underlying cause is this exception:

ClassCastException: attempting to cast jar:file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/rt.jar!/javax/xml/bind/JAXBContext.class to jar:file:/C:/Program%20Files/Java/jdk1.8.0_101/jre/lib/rt.jar!/javax/xml/bind/JAXBContext.class.  Please make sure that you are specifying the proper ClassLoader.

I can work around this by adding the parameter -DforkCount=1 to the Maven command that runs the tests.

It is not clear to me whether this is an issue only with my environment or instead this would affect the automated build/test within ONAP.

Patch-set: 1